name: Terraform Pipeline

# =======================================================
# CONFIGURACIÓN BÁSICA DEL PIPELINE DE INFRAESTRUCTURA
# =======================================================

# Este pipeline se ejecutará automáticamente cuando:
# - Se realicen cambios en la rama 'master'
# - Y los cambios afecten archivos dentro del directorio 'terraform/'
on:
  push:
    branches:
      - '*'
    paths:
      - '../../terraform/**'

# Variables reutilizables a lo largo del workflow
env:
  TERRAFORM_DIR: 'terraform' # Carpeta donde están los archivos .tf
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} # Credenciales de Azure configuradas en GitHub Secrets

jobs:
  # ==============================================
  # ETAPA 1: VALIDACIÓN DE INFRAESTRUCTURA
  # ==============================================
  validate:
    name: '1. Validación de Infraestructura'
    runs-on: ubuntu-latest # Agente de ejecución (máquina virtual en la nube)
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      # Paso 4: Inicializar Terraform
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ${{ env.TERRAFORM_DIR }}

      # Paso 5: Validar la sintaxis de los archivos Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TERRAFORM_DIR }}

      # Paso 6: Generar el plan de ejecución
      # - Muestra los cambios que se aplicarían sin ejecutarlos
      # - Guarda el plan como archivo binario `tfplan`
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TERRAFORM_DIR }}

      # Paso 7: Subir el archivo tfplan como artefacto
      # - Esto permite usar el mismo plan en la siguiente etapa
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ${{ env.TERRAFORM_DIR }}/tfplan

  # ==============================================
  # ETAPA 2: APLICACIÓN DE CAMBIOS EN AZURE
  # ==============================================
  apply:
    name: '2. Aplicar Infraestructura'
    needs: validate # Solo se ejecuta si la etapa de validación fue exitosa
    if: success()
    runs-on: ubuntu-latest # Agente de ejecución

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      # Paso 4: Descargar el artefacto tfplan generado anteriormente
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ${{ env.TERRAFORM_DIR }}

      # Paso 5: Inicializar Terraform en esta etapa también
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ${{ env.TERRAFORM_DIR }}

      # Paso 6: Aplicar la infraestructura usando el archivo de plan
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
        working-directory: ${{ env.TERRAFORM_DIR }}